export type Topic = {
  slug: string;
  title: string;
  label: string;
  description: string;
  href: string;
};

export type CategoryPageData = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  topics: Topic[];
  nextTitle: string;
  nextDescription: string;
  parentHref?: string;
  parentLabel?: string;
};

const topic = (slug: string, title: string, label: string, description: string, href: string): Topic => ({ slug, title, label, description, href });

export const categoryPages: Record<string, CategoryPageData> = {
  explore: {
    slug: "explore", eyebrow: "The knowledge map", title: "Explore the Atlas", description: "A structured starting point for geography, exam preparation, language, research and the ideas connecting them.", topics: [
      topic("bcs", "BCS Preparation", "Exam intelligence", "Build a clear path through the syllabus with focused study domains.", "/bcs"),
      topic("geography", "Geography", "Spatial knowledge", "Maps, regions, physical systems and the forces shaping place.", "/geography"),
      topic("international-affairs", "International Affairs", "Global perspective", "Events, institutions and ideas that connect the world.", "/international-affairs"),
      topic("english", "English & IELTS", "Language lab", "Sharper language, richer vocabulary and exam-ready communication.", "/english"),
      topic("research", "Research", "Field notes", "A home for questions, methods, GIS and work in progress.", "/research"),
    ], nextTitle: "Start with a question", nextDescription: "The Atlas will grow around the subjects you return to most. Choose a domain and begin building context.",
  },
  bcs: { slug: "bcs", eyebrow: "The command center", title: "BCS Preparation", description: "Turn a wide syllabus into a visible, connected path through knowledge, practice and revision.", topics: [
    topic("bangladesh-affairs", "Bangladesh Affairs", "National context", "History, society, economy and identity of Bangladesh.", "/bcs/bangladesh-affairs"), topic("international-affairs", "International Affairs", "Global perspective", "Events, institutions and ideas that connect the world.", "/bcs/international-affairs"), topic("geography-environment", "Geography & Environment", "Spatial knowledge", "Physical systems, resources, environment and Bangladesh geography.", "/bcs/geography-environment"), topic("english", "English", "Language lab", "Grammar, vocabulary and communication for the competitive exam.", "/bcs/english"), topic("bangla", "Bangla", "Language & literature", "Language, literature and the cultural foundations of Bangladesh.", "/bcs/bangla"), topic("science-ict", "Science & ICT", "Future signals", "Core science concepts and the digital world around us.", "/bcs/science-ict"), topic("ethics-governance", "Ethics & Governance", "Public purpose", "The principles, institutions and responsibilities of public service.", "/bcs/ethics-governance"),
  ], nextTitle: "A focused preparation loop", nextDescription: "Next, each domain will grow into notes, practice sets and revision trails that make progress easier to see.", },
  geography: { slug: "geography", eyebrow: "The spatial atlas", title: "Geography", description: "Understand places through patterns, processes and the relationships between people and their environments.", topics: [
    topic("physical", "Physical Geography", "Earth systems", "Landforms, climate, oceans and the living systems of the planet.", "/geography/physical"), topic("human", "Human Geography", "People & place", "Population, culture, cities, migration and spatial identity.", "/geography/human"), topic("economic", "Economic Geography", "Networks & resources", "Production, trade, resources and the geography of opportunity.", "/geography/economic"), topic("environmental", "Environmental Geography", "Planetary balance", "Human impact, risk, conservation and sustainable futures.", "/geography/environmental"), topic("bangladesh", "Geography of Bangladesh", "A living delta", "The rivers, regions, settlements and systems of Bangladesh.", "/geography/bangladesh"),
  ], nextTitle: "Read the world in layers", nextDescription: "The next stage adds maps, regional explainers and connected geographic concepts to each part of the Atlas.", },
  english: { slug: "english", eyebrow: "The language lab", title: "English & IELTS", description: "Build precise grammar, a richer working vocabulary and the confidence to communicate clearly.", topics: [
    topic("grammar", "Grammar", "Structure", "Sentence patterns, usage and the rules that make meaning precise.", "/english/grammar"), topic("vocabulary", "Vocabulary", "Word power", "Learn words through context, nuance and memorable connections.", "/english/vocabulary"), topic("literature", "Literature", "Language & culture", "Authors, movements and the ideas that shape English expression.", "/english/literature"), topic("ielts", "IELTS", "Exam readiness", "A practical path through reading, writing, listening and speaking.", "/english/ielts"),
  ], nextTitle: "Make language active", nextDescription: "Practice materials and short revision routines will turn each language area into a repeatable daily habit.", },
  "international-affairs": { slug: "international-affairs", eyebrow: "The global desk", title: "International Affairs", description: "Follow the institutions, events and ideas that shape a connected world.", topics: [topic("world-order", "World Order", "Systems", "Power, alliances and the changing architecture of global affairs.", "/international-affairs"), topic("institutions", "Global Institutions", "Cooperation", "The organizations and agreements that organize international action.", "/international-affairs"), topic("current-affairs", "Current Affairs", "Signals", "A structured place for important events and their wider context.", "/international-affairs")], nextTitle: "Context before headlines", nextDescription: "This desk will become a living briefing space for linking current events to history, geography and policy.", },
  research: { slug: "research", eyebrow: "The field notes", title: "Research", description: "A quiet workspace for questions, methods, geographic thinking and work in progress.", topics: [topic("gis", "GIS & Mapping", "Methods", "Spatial data, mapping workflows and geographic analysis.", "/research"), topic("fieldwork", "Fieldwork", "Observation", "Questions and notes gathered from places, people and landscapes.", "/research"), topic("reading-room", "Reading Room", "References", "A growing index of papers, books and useful sources.", "/research")], nextTitle: "Questions worth keeping", nextDescription: "Research tools and reading notes will gradually connect the Atlas to longer-form academic work.", },
  about: { slug: "about", eyebrow: "The idea behind the Atlas", title: "About Sajib Atlas", description: "Sajib Atlas is a personal knowledge platform for learning across geography, BCS preparation, international affairs, English, science and research.", topics: [topic("purpose", "A connected system", "Why it exists", "Knowledge becomes more useful when ideas can be found, revisited and connected.", "/about"), topic("approach", "Structured learning", "How it grows", "The platform is being shaped around clear domains, useful notes and steady practice.", "/about")], nextTitle: "Still being mapped", nextDescription: "Sajib Atlas is an evolving project. New notes, tools and connections will take shape as the knowledge system grows.", },
};

export const nestedPages: Record<string, CategoryPageData> = {
  "bcs/bangladesh-affairs": { slug: "bangladesh-affairs", eyebrow: "BCS / national context", title: "Bangladesh Affairs", description: "Build context around the history, society, economy and identity of Bangladesh.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("history", "History & Liberation", "Foundations", "Key periods, movements and milestones in Bangladesh's story.", "/bcs/bangladesh-affairs"), topic("economy", "Economy & Development", "Current structure", "The sectors, indicators and challenges shaping national development.", "/bcs/bangladesh-affairs"), topic("constitution", "Constitution & State", "Civic knowledge", "Institutions, rights and the framework of public life.", "/bcs/bangladesh-affairs")], nextTitle: "Build a national picture", nextDescription: "These topics will become concise, revision-friendly explainers with timelines and key facts." },
  "bcs/international-affairs": { slug: "international-affairs", eyebrow: "BCS / global perspective", title: "International Affairs", description: "Connect global events to institutions, geography, history and policy.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("diplomacy", "Diplomacy & Relations", "Core concepts", "The language and practice of states working across borders.", "/bcs/international-affairs"), topic("organizations", "International Organizations", "Institutions", "The roles and structures behind global cooperation.", "/bcs/international-affairs")], nextTitle: "Read beyond the headline", nextDescription: "Briefings and revision prompts will make major international themes easier to revisit." },
  "bcs/geography-environment": { slug: "geography-environment", eyebrow: "BCS / spatial knowledge", title: "Geography & Environment", description: "Study the physical systems, resources and environmental questions that shape Bangladesh and the world.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("physical-systems", "Physical Systems", "Earth science", "Climate, landforms, rivers and the forces shaping landscapes.", "/bcs/geography-environment"), topic("resources", "Resources & Risk", "Applied geography", "Natural resources, hazards and the choices behind resilience.", "/bcs/geography-environment")], nextTitle: "Think in systems", nextDescription: "Maps, diagrams and short concept notes will turn broad geography into connected recall." },
  "bcs/english": { slug: "english", eyebrow: "BCS / language lab", title: "English", description: "A focused space for the grammar, vocabulary and comprehension needed for BCS preparation.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("grammar", "Grammar", "Structure", "Usage and sentence patterns for precise answers.", "/english/grammar"), topic("vocabulary", "Vocabulary", "Word power", "High-value words learned through context and repetition.", "/english/vocabulary")], nextTitle: "Practice with precision", nextDescription: "Short drills and revision lists will make language work easier to fit into a study day." },
  "bcs/bangla": { slug: "bangla", eyebrow: "BCS / language & literature", title: "Bangla", description: "Explore Bangla language, literature and the cultural foundations of Bangladesh.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("language", "Bangla Language", "Usage", "Grammar, usage and the structure of Bangla expression.", "/bcs/bangla"), topic("literature", "Bangla Literature", "Culture", "Writers, movements and works that shape the literary tradition.", "/bcs/bangla")], nextTitle: "A richer reading list", nextDescription: "This section will grow into concise author notes, literary timelines and practice prompts." },
  "bcs/science-ict": { slug: "science-ict", eyebrow: "BCS / future signals", title: "Science & ICT", description: "Build practical understanding of core science and the digital systems shaping everyday life.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("general-science", "General Science", "Core concepts", "The essential ideas behind the natural world and human health.", "/bcs/science-ict"), topic("ict", "ICT & Digital Systems", "Technology", "Networks, information and the tools transforming society.", "/bcs/science-ict")], nextTitle: "Concepts you can use", nextDescription: "Future notes will pair short explanations with diagrams, examples and practice questions." },
  "bcs/ethics-governance": { slug: "ethics-governance", eyebrow: "BCS / public purpose", title: "Ethics & Governance", description: "Understand the principles, institutions and responsibilities of public service.", parentHref: "/bcs", parentLabel: "BCS Preparation", topics: [topic("ethics", "Ethics", "Principles", "Values and reasoning for responsible public action.", "/bcs/ethics-governance"), topic("governance", "Governance", "Institutions", "Accountability, administration and the work of the state.", "/bcs/ethics-governance")], nextTitle: "From principle to practice", nextDescription: "Case studies and concise frameworks will make abstract governance ideas easier to apply." },
};

const geographyNested = [["physical", "Physical Geography", "Earth systems", "Landforms, climate, oceans and the living systems of the planet."], ["human", "Human Geography", "People & place", "Population, culture, cities, migration and spatial identity."], ["economic", "Economic Geography", "Networks & resources", "Production, trade, resources and the geography of opportunity."], ["environmental", "Environmental Geography", "Planetary balance", "Human impact, risk, conservation and sustainable futures."], ["bangladesh", "Geography of Bangladesh", "A living delta", "The rivers, regions, settlements and systems of Bangladesh."]];
for (const [slug, title, label, description] of geographyNested) nestedPages[`geography/${slug}`] = { slug, eyebrow: `Geography / ${label}`, title, description, parentHref: "/geography", parentLabel: "Geography", topics: [topic(`${slug}-foundations`, `${title} Foundations`, "Core concepts", description, `/geography/${slug}`), topic(`${slug}-connections`, "Connected systems", "Patterns", "See how this domain links people, place, process and change.", `/geography/${slug}`)], nextTitle: "Maps are next", nextDescription: "This section will grow with diagrams, regional examples and visual explainers." };
const englishNested = [["grammar", "Grammar", "Structure", "Sentence patterns, usage and the rules that make meaning precise."], ["vocabulary", "Vocabulary", "Word power", "Learn words through context, nuance and memorable connections."], ["literature", "Literature", "Language & culture", "Authors, movements and the ideas that shape English expression."], ["ielts", "IELTS", "Exam readiness", "A practical path through reading, writing, listening and speaking."]];
for (const [slug, title, label, description] of englishNested) nestedPages[`english/${slug}`] = { slug, eyebrow: `English / ${label}`, title, description, parentHref: "/english", parentLabel: "English & IELTS", topics: [topic(`${slug}-guide`, `${title} Guide`, "Core concepts", description, `/english/${slug}`), topic(`${slug}-practice`, "Practice space", "Application", "Short exercises and revision prompts for active learning.", `/english/${slug}`)], nextTitle: "Practice makes language", nextDescription: "Examples, drills and revision paths will be added here as the language lab expands." };

export const nestedPaths = Object.keys(nestedPages);
